services:
  # Temporal
  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.22.3
    ports:
      - "7233:7233"
      - "7234:7234"
      - "7235:7235"
      - "7236:7236"
      - "8233:8233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
    depends_on:
      - temporal-db

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1.27.1
    depends_on:
      - temporal

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:2.21.3
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    depends_on:
      - temporal

  # PostgreSQL for Temporal
  temporal-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
