query Workspace($rowId: UUID!, $userId: UUID!) {
  workspace(rowId: $rowId) {
    rowId
    name
    slug
    tier
    subscriptionId
    workspaceUsers(condition: { userId: $userId }) {
      nodes {
        role
      }
    }
    workflows(orderBy: NAME_ASC) {
      totalCount
      nodes {
        rowId
        name
        isActive
        createdAt
        updatedAt
      }
    }
    integrations(orderBy: NAME_ASC) {
      totalCount
      nodes {
        rowId
        name
        type
        isEnabled
      }
    }
    plugins(orderBy: NAME_ASC) {
      totalCount
      nodes {
        rowId
        name
        version
        isEnabled
      }
    }
  }
}
