query Integrations($workspaceId: UUID!, $limit: Int) {
  integrations(
    condition: { workspaceId: $workspaceId }
    orderBy: NAME_ASC
    first: $limit
  ) {
    nodes {
      rowId
      name
      type
      definitionId
      isEnabled
      createdAt
      updatedAt
      integrationDefinition {
        id
        name
        description
        iconUrl
        category
        authType
        keepAlive
      }
    }
    totalCount
  }
}

query Integration($id: UUID!) {
  integration(rowId: $id) {
    rowId
    name
    type
    definitionId
    isEnabled
    config
    createdAt
    updatedAt
    integrationDefinition {
      id
      name
      description
      iconUrl
      category
      authType
      authFields
      keepAlive
    }
  }
}

query WorkspaceIntegrationsByType($workspaceId: UUID!) {
  integrations(condition: { workspaceId: $workspaceId }) {
    nodes {
      rowId
      type
      definitionId
      isEnabled
    }
  }
}
