/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as ApiExecuteWorkflowRouteImport } from './routes/api/execute-workflow'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as AuthWorkspacesIndexRouteImport } from './routes/_auth/workspaces/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicOauthErrorRouteImport } from './routes/_public/oauth/error'
import { Route as PublicOauthCallbackRouteImport } from './routes/_public/oauth/callback'
import { Route as AuthWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/index'
import { Route as ApiRunsRunIdStreamRouteImport } from './routes/api/runs/$runId/stream'
import { Route as AuthWorkspacesWorkspaceSlugSettingsRouteImport } from './routes/_auth/workspaces/$workspaceSlug/settings'
import { Route as AuthWorkspacesWorkspaceSlugWorkflowsIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/workflows/index'
import { Route as AuthWorkspacesWorkspaceSlugIntegrationsIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/integrations/index'
import { Route as ApiWebhooksWorkflowWorkflowIdSecretRouteImport } from './routes/api/webhooks/workflow/$workflowId/$secret'
import { Route as AuthWorkspacesWorkspaceSlugWorkflowsNewRouteImport } from './routes/_auth/workspaces/$workspaceSlug/workflows/new'
import { Route as AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRouteImport } from './routes/_auth/workspaces/$workspaceSlug/workflows/$workflowId'
import { Route as AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRouteImport } from './routes/_auth/workspaces/$workspaceSlug/integrations/$integrationId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteWorkflowRoute = ApiExecuteWorkflowRouteImport.update({
  id: '/api/execute-workflow',
  path: '/api/execute-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const AuthWorkspacesIndexRoute = AuthWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOauthErrorRoute = PublicOauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOauthCallbackRoute = PublicOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const AuthWorkspacesWorkspaceSlugIndexRoute =
  AuthWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/',
    path: '/workspaces/$workspaceSlug/',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiRunsRunIdStreamRoute = ApiRunsRunIdStreamRouteImport.update({
  id: '/api/runs/$runId/stream',
  path: '/api/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspacesWorkspaceSlugSettingsRoute =
  AuthWorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/workspaces/$workspaceSlug/settings',
    path: '/workspaces/$workspaceSlug/settings',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute =
  AuthWorkspacesWorkspaceSlugWorkflowsIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/workflows/',
    path: '/workspaces/$workspaceSlug/workflows/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute =
  AuthWorkspacesWorkspaceSlugIntegrationsIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/integrations/',
    path: '/workspaces/$workspaceSlug/integrations/',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiWebhooksWorkflowWorkflowIdSecretRoute =
  ApiWebhooksWorkflowWorkflowIdSecretRouteImport.update({
    id: '/api/webhooks/workflow/$workflowId/$secret',
    path: '/api/webhooks/workflow/$workflowId/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthWorkspacesWorkspaceSlugWorkflowsNewRoute =
  AuthWorkspacesWorkspaceSlugWorkflowsNewRouteImport.update({
    id: '/workspaces/$workspaceSlug/workflows/new',
    path: '/workspaces/$workspaceSlug/workflows/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute =
  AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRouteImport.update({
    id: '/workspaces/$workspaceSlug/workflows/$workflowId',
    path: '/workspaces/$workspaceSlug/workflows/$workflowId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute =
  AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRouteImport.update({
    id: '/workspaces/$workspaceSlug/integrations/$integrationId',
    path: '/workspaces/$workspaceSlug/integrations/$integrationId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/pricing': typeof PublicPricingRoute
  '/api/execute-workflow': typeof ApiExecuteWorkflowRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/': typeof AuthWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/workspaces/$workspaceSlug/': typeof AuthWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/integrations/$integrationId': typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  '/workspaces/$workspaceSlug/workflows/$workflowId': typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  '/workspaces/$workspaceSlug/workflows/new': typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  '/api/webhooks/workflow/$workflowId/$secret': typeof ApiWebhooksWorkflowWorkflowIdSecretRoute
  '/workspaces/$workspaceSlug/integrations/': typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  '/workspaces/$workspaceSlug/workflows/': typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/pricing': typeof PublicPricingRoute
  '/api/execute-workflow': typeof ApiExecuteWorkflowRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/workspaces/$workspaceSlug': typeof AuthWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/integrations/$integrationId': typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  '/workspaces/$workspaceSlug/workflows/$workflowId': typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  '/workspaces/$workspaceSlug/workflows/new': typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  '/api/webhooks/workflow/$workflowId/$secret': typeof ApiWebhooksWorkflowWorkflowIdSecretRoute
  '/workspaces/$workspaceSlug/integrations': typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  '/workspaces/$workspaceSlug/workflows': typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/pricing': typeof PublicPricingRoute
  '/api/execute-workflow': typeof ApiExecuteWorkflowRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/oauth/callback': typeof PublicOauthCallbackRoute
  '/_public/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/workspaces/': typeof AuthWorkspacesIndexRoute
  '/_auth/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/_auth/workspaces/$workspaceSlug/': typeof AuthWorkspacesWorkspaceSlugIndexRoute
  '/_auth/workspaces/$workspaceSlug/integrations/$integrationId': typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  '/_auth/workspaces/$workspaceSlug/workflows/$workflowId': typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  '/_auth/workspaces/$workspaceSlug/workflows/new': typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  '/api/webhooks/workflow/$workflowId/$secret': typeof ApiWebhooksWorkflowWorkflowIdSecretRoute
  '/_auth/workspaces/$workspaceSlug/integrations/': typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  '/_auth/workspaces/$workspaceSlug/workflows/': typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/api/execute-workflow'
    | '/api/send-email'
    | '/oauth/callback'
    | '/oauth/error'
    | '/api/auth/$'
    | '/workspaces/'
    | '/workspaces/$workspaceSlug/settings'
    | '/api/runs/$runId/stream'
    | '/workspaces/$workspaceSlug/'
    | '/workspaces/$workspaceSlug/integrations/$integrationId'
    | '/workspaces/$workspaceSlug/workflows/$workflowId'
    | '/workspaces/$workspaceSlug/workflows/new'
    | '/api/webhooks/workflow/$workflowId/$secret'
    | '/workspaces/$workspaceSlug/integrations/'
    | '/workspaces/$workspaceSlug/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/api/execute-workflow'
    | '/api/send-email'
    | '/oauth/callback'
    | '/oauth/error'
    | '/api/auth/$'
    | '/workspaces'
    | '/workspaces/$workspaceSlug/settings'
    | '/api/runs/$runId/stream'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/$workspaceSlug/integrations/$integrationId'
    | '/workspaces/$workspaceSlug/workflows/$workflowId'
    | '/workspaces/$workspaceSlug/workflows/new'
    | '/api/webhooks/workflow/$workflowId/$secret'
    | '/workspaces/$workspaceSlug/integrations'
    | '/workspaces/$workspaceSlug/workflows'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_public/pricing'
    | '/api/execute-workflow'
    | '/api/send-email'
    | '/_public/'
    | '/_public/oauth/callback'
    | '/_public/oauth/error'
    | '/api/auth/$'
    | '/_auth/workspaces/'
    | '/_auth/workspaces/$workspaceSlug/settings'
    | '/api/runs/$runId/stream'
    | '/_auth/workspaces/$workspaceSlug/'
    | '/_auth/workspaces/$workspaceSlug/integrations/$integrationId'
    | '/_auth/workspaces/$workspaceSlug/workflows/$workflowId'
    | '/_auth/workspaces/$workspaceSlug/workflows/new'
    | '/api/webhooks/workflow/$workflowId/$secret'
    | '/_auth/workspaces/$workspaceSlug/integrations/'
    | '/_auth/workspaces/$workspaceSlug/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiExecuteWorkflowRoute: typeof ApiExecuteWorkflowRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRunsRunIdStreamRoute: typeof ApiRunsRunIdStreamRoute
  ApiWebhooksWorkflowWorkflowIdSecretRoute: typeof ApiWebhooksWorkflowWorkflowIdSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute-workflow': {
      id: '/api/execute-workflow'
      path: '/api/execute-workflow'
      fullPath: '/api/execute-workflow'
      preLoaderRoute: typeof ApiExecuteWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/workspaces/': {
      id: '/_auth/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthWorkspacesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/oauth/error': {
      id: '/_public/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof PublicOauthErrorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/oauth/callback': {
      id: '/_public/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof PublicOauthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/workspaces/$workspaceSlug/': {
      id: '/_auth/workspaces/$workspaceSlug/'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/runs/$runId/stream': {
      id: '/api/runs/$runId/stream'
      path: '/api/runs/$runId/stream'
      fullPath: '/api/runs/$runId/stream'
      preLoaderRoute: typeof ApiRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/workspaces/$workspaceSlug/settings': {
      id: '/_auth/workspaces/$workspaceSlug/settings'
      path: '/workspaces/$workspaceSlug/settings'
      fullPath: '/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/workflows/': {
      id: '/_auth/workspaces/$workspaceSlug/workflows/'
      path: '/workspaces/$workspaceSlug/workflows'
      fullPath: '/workspaces/$workspaceSlug/workflows/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/integrations/': {
      id: '/_auth/workspaces/$workspaceSlug/integrations/'
      path: '/workspaces/$workspaceSlug/integrations'
      fullPath: '/workspaces/$workspaceSlug/integrations/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/webhooks/workflow/$workflowId/$secret': {
      id: '/api/webhooks/workflow/$workflowId/$secret'
      path: '/api/webhooks/workflow/$workflowId/$secret'
      fullPath: '/api/webhooks/workflow/$workflowId/$secret'
      preLoaderRoute: typeof ApiWebhooksWorkflowWorkflowIdSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/workspaces/$workspaceSlug/workflows/new': {
      id: '/_auth/workspaces/$workspaceSlug/workflows/new'
      path: '/workspaces/$workspaceSlug/workflows/new'
      fullPath: '/workspaces/$workspaceSlug/workflows/new'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/workflows/$workflowId': {
      id: '/_auth/workspaces/$workspaceSlug/workflows/$workflowId'
      path: '/workspaces/$workspaceSlug/workflows/$workflowId'
      fullPath: '/workspaces/$workspaceSlug/workflows/$workflowId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/integrations/$integrationId': {
      id: '/_auth/workspaces/$workspaceSlug/integrations/$integrationId'
      path: '/workspaces/$workspaceSlug/integrations/$integrationId'
      fullPath: '/workspaces/$workspaceSlug/integrations/$integrationId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthWorkspacesIndexRoute: typeof AuthWorkspacesIndexRoute
  AuthWorkspacesWorkspaceSlugSettingsRoute: typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  AuthWorkspacesWorkspaceSlugIndexRoute: typeof AuthWorkspacesWorkspaceSlugIndexRoute
  AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  AuthWorkspacesWorkspaceSlugWorkflowsNewRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWorkspacesIndexRoute: AuthWorkspacesIndexRoute,
  AuthWorkspacesWorkspaceSlugSettingsRoute:
    AuthWorkspacesWorkspaceSlugSettingsRoute,
  AuthWorkspacesWorkspaceSlugIndexRoute: AuthWorkspacesWorkspaceSlugIndexRoute,
  AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute:
    AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute,
  AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute:
    AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute,
  AuthWorkspacesWorkspaceSlugWorkflowsNewRoute:
    AuthWorkspacesWorkspaceSlugWorkflowsNewRoute,
  AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute:
    AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute,
  AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute:
    AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicOauthCallbackRoute: typeof PublicOauthCallbackRoute
  PublicOauthErrorRoute: typeof PublicOauthErrorRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOauthCallbackRoute: PublicOauthCallbackRoute,
  PublicOauthErrorRoute: PublicOauthErrorRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiExecuteWorkflowRoute: ApiExecuteWorkflowRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRunsRunIdStreamRoute: ApiRunsRunIdStreamRoute,
  ApiWebhooksWorkflowWorkflowIdSecretRoute:
    ApiWebhooksWorkflowWorkflowIdSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
