/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiHealthRouteImport } from './routes/api/[_]health'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces/index'
import { Route as AppAtChar123workspaceSlugChar125IndexRouteImport } from './routes/_app/@{$workspaceSlug}/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicOauthErrorRouteImport } from './routes/_public/oauth/error'
import { Route as PublicOauthCallbackRouteImport } from './routes/_public/oauth/callback'
import { Route as AppAtChar123workspaceSlugChar125WorkflowsIndexRouteImport } from './routes/_app/@{$workspaceSlug}/workflows/index'
import { Route as AppAtChar123workspaceSlugChar125PluginsIndexRouteImport } from './routes/_app/@{$workspaceSlug}/plugins/index'
import { Route as AppAtChar123workspaceSlugChar125MonitoringIndexRouteImport } from './routes/_app/@{$workspaceSlug}/monitoring/index'
import { Route as AppAtChar123workspaceSlugChar125IntegrationsIndexRouteImport } from './routes/_app/@{$workspaceSlug}/integrations/index'
import { Route as AppAtChar123workspaceSlugChar125EventsIndexRouteImport } from './routes/_app/@{$workspaceSlug}/events/index'
import { Route as AppAtChar123workspaceSlugChar125DlqIndexRouteImport } from './routes/_app/@{$workspaceSlug}/dlq/index'
import { Route as ApiRunsRunIdStreamRouteImport } from './routes/api/runs/$runId/stream'
import { Route as AppAtChar123workspaceSlugChar125Char126SettingsRouteImport } from './routes/_app/@{$workspaceSlug}/~/settings'
import { Route as AppAtChar123workspaceSlugChar125WorkflowsNewRouteImport } from './routes/_app/@{$workspaceSlug}/workflows/new'
import { Route as AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRouteImport } from './routes/_app/@{$workspaceSlug}/workflows/$workflowId'
import { Route as AppAtChar123workspaceSlugChar125PluginsPluginIdRouteImport } from './routes/_app/@{$workspaceSlug}/plugins/$pluginId'
import { Route as AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRouteImport } from './routes/_app/@{$workspaceSlug}/integrations/$integrationId'
import { Route as AppAtChar123workspaceSlugChar125EventsSandboxRouteImport } from './routes/_app/@{$workspaceSlug}/events/sandbox'
import { Route as AppAtChar123workspaceSlugChar125EventsDiffRouteImport } from './routes/_app/@{$workspaceSlug}/events/diff'
import { Route as AppAtChar123workspaceSlugChar125EventsSchemaNameRouteImport } from './routes/_app/@{$workspaceSlug}/events/$schemaName'
import { Route as AppAtChar123workspaceSlugChar125Char126MembersIndexRouteImport } from './routes/_app/@{$workspaceSlug}/~/members/index'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/_health',
  path: '/api/_health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppAtChar123workspaceSlugChar125IndexRoute =
  AppAtChar123workspaceSlugChar125IndexRouteImport.update({
    id: '/@{$workspaceSlug}/',
    path: '/@{$workspaceSlug}/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOauthErrorRoute = PublicOauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOauthCallbackRoute = PublicOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const AppAtChar123workspaceSlugChar125WorkflowsIndexRoute =
  AppAtChar123workspaceSlugChar125WorkflowsIndexRouteImport.update({
    id: '/@{$workspaceSlug}/workflows/',
    path: '/@{$workspaceSlug}/workflows/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125PluginsIndexRoute =
  AppAtChar123workspaceSlugChar125PluginsIndexRouteImport.update({
    id: '/@{$workspaceSlug}/plugins/',
    path: '/@{$workspaceSlug}/plugins/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125MonitoringIndexRoute =
  AppAtChar123workspaceSlugChar125MonitoringIndexRouteImport.update({
    id: '/@{$workspaceSlug}/monitoring/',
    path: '/@{$workspaceSlug}/monitoring/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125IntegrationsIndexRoute =
  AppAtChar123workspaceSlugChar125IntegrationsIndexRouteImport.update({
    id: '/@{$workspaceSlug}/integrations/',
    path: '/@{$workspaceSlug}/integrations/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125EventsIndexRoute =
  AppAtChar123workspaceSlugChar125EventsIndexRouteImport.update({
    id: '/@{$workspaceSlug}/events/',
    path: '/@{$workspaceSlug}/events/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125DlqIndexRoute =
  AppAtChar123workspaceSlugChar125DlqIndexRouteImport.update({
    id: '/@{$workspaceSlug}/dlq/',
    path: '/@{$workspaceSlug}/dlq/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiRunsRunIdStreamRoute = ApiRunsRunIdStreamRouteImport.update({
  id: '/api/runs/$runId/stream',
  path: '/api/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAtChar123workspaceSlugChar125Char126SettingsRoute =
  AppAtChar123workspaceSlugChar125Char126SettingsRouteImport.update({
    id: '/@{$workspaceSlug}/~/settings',
    path: '/@{$workspaceSlug}/~/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125WorkflowsNewRoute =
  AppAtChar123workspaceSlugChar125WorkflowsNewRouteImport.update({
    id: '/@{$workspaceSlug}/workflows/new',
    path: '/@{$workspaceSlug}/workflows/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute =
  AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRouteImport.update({
    id: '/@{$workspaceSlug}/workflows/$workflowId',
    path: '/@{$workspaceSlug}/workflows/$workflowId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125PluginsPluginIdRoute =
  AppAtChar123workspaceSlugChar125PluginsPluginIdRouteImport.update({
    id: '/@{$workspaceSlug}/plugins/$pluginId',
    path: '/@{$workspaceSlug}/plugins/$pluginId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute =
  AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRouteImport.update({
    id: '/@{$workspaceSlug}/integrations/$integrationId',
    path: '/@{$workspaceSlug}/integrations/$integrationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125EventsSandboxRoute =
  AppAtChar123workspaceSlugChar125EventsSandboxRouteImport.update({
    id: '/@{$workspaceSlug}/events/sandbox',
    path: '/@{$workspaceSlug}/events/sandbox',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125EventsDiffRoute =
  AppAtChar123workspaceSlugChar125EventsDiffRouteImport.update({
    id: '/@{$workspaceSlug}/events/diff',
    path: '/@{$workspaceSlug}/events/diff',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125EventsSchemaNameRoute =
  AppAtChar123workspaceSlugChar125EventsSchemaNameRouteImport.update({
    id: '/@{$workspaceSlug}/events/$schemaName',
    path: '/@{$workspaceSlug}/events/$schemaName',
    getParentRoute: () => AppRoute,
  } as any)
const AppAtChar123workspaceSlugChar125Char126MembersIndexRoute =
  AppAtChar123workspaceSlugChar125Char126MembersIndexRouteImport.update({
    id: '/@{$workspaceSlug}/~/members/',
    path: '/@{$workspaceSlug}/~/members/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/demo': typeof DemoRoute
  '/pricing': typeof PublicPricingRoute
  '/api/_health': typeof ApiHealthRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/@{$workspaceSlug}/': typeof AppAtChar123workspaceSlugChar125IndexRoute
  '/workspaces/': typeof AppWorkspacesIndexRoute
  '/@{$workspaceSlug}/events/$schemaName': typeof AppAtChar123workspaceSlugChar125EventsSchemaNameRoute
  '/@{$workspaceSlug}/events/diff': typeof AppAtChar123workspaceSlugChar125EventsDiffRoute
  '/@{$workspaceSlug}/events/sandbox': typeof AppAtChar123workspaceSlugChar125EventsSandboxRoute
  '/@{$workspaceSlug}/integrations/$integrationId': typeof AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute
  '/@{$workspaceSlug}/plugins/$pluginId': typeof AppAtChar123workspaceSlugChar125PluginsPluginIdRoute
  '/@{$workspaceSlug}/workflows/$workflowId': typeof AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute
  '/@{$workspaceSlug}/workflows/new': typeof AppAtChar123workspaceSlugChar125WorkflowsNewRoute
  '/@{$workspaceSlug}/~/settings': typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/@{$workspaceSlug}/dlq/': typeof AppAtChar123workspaceSlugChar125DlqIndexRoute
  '/@{$workspaceSlug}/events/': typeof AppAtChar123workspaceSlugChar125EventsIndexRoute
  '/@{$workspaceSlug}/integrations/': typeof AppAtChar123workspaceSlugChar125IntegrationsIndexRoute
  '/@{$workspaceSlug}/monitoring/': typeof AppAtChar123workspaceSlugChar125MonitoringIndexRoute
  '/@{$workspaceSlug}/plugins/': typeof AppAtChar123workspaceSlugChar125PluginsIndexRoute
  '/@{$workspaceSlug}/workflows/': typeof AppAtChar123workspaceSlugChar125WorkflowsIndexRoute
  '/@{$workspaceSlug}/~/members/': typeof AppAtChar123workspaceSlugChar125Char126MembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/demo': typeof DemoRoute
  '/pricing': typeof PublicPricingRoute
  '/api/_health': typeof ApiHealthRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/@{$workspaceSlug}': typeof AppAtChar123workspaceSlugChar125IndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/@{$workspaceSlug}/events/$schemaName': typeof AppAtChar123workspaceSlugChar125EventsSchemaNameRoute
  '/@{$workspaceSlug}/events/diff': typeof AppAtChar123workspaceSlugChar125EventsDiffRoute
  '/@{$workspaceSlug}/events/sandbox': typeof AppAtChar123workspaceSlugChar125EventsSandboxRoute
  '/@{$workspaceSlug}/integrations/$integrationId': typeof AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute
  '/@{$workspaceSlug}/plugins/$pluginId': typeof AppAtChar123workspaceSlugChar125PluginsPluginIdRoute
  '/@{$workspaceSlug}/workflows/$workflowId': typeof AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute
  '/@{$workspaceSlug}/workflows/new': typeof AppAtChar123workspaceSlugChar125WorkflowsNewRoute
  '/@{$workspaceSlug}/~/settings': typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/@{$workspaceSlug}/dlq': typeof AppAtChar123workspaceSlugChar125DlqIndexRoute
  '/@{$workspaceSlug}/events': typeof AppAtChar123workspaceSlugChar125EventsIndexRoute
  '/@{$workspaceSlug}/integrations': typeof AppAtChar123workspaceSlugChar125IntegrationsIndexRoute
  '/@{$workspaceSlug}/monitoring': typeof AppAtChar123workspaceSlugChar125MonitoringIndexRoute
  '/@{$workspaceSlug}/plugins': typeof AppAtChar123workspaceSlugChar125PluginsIndexRoute
  '/@{$workspaceSlug}/workflows': typeof AppAtChar123workspaceSlugChar125WorkflowsIndexRoute
  '/@{$workspaceSlug}/~/members': typeof AppAtChar123workspaceSlugChar125Char126MembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/demo': typeof DemoRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/api/_health': typeof ApiHealthRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/oauth/callback': typeof PublicOauthCallbackRoute
  '/_public/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/@{$workspaceSlug}/': typeof AppAtChar123workspaceSlugChar125IndexRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
  '/_app/@{$workspaceSlug}/events/$schemaName': typeof AppAtChar123workspaceSlugChar125EventsSchemaNameRoute
  '/_app/@{$workspaceSlug}/events/diff': typeof AppAtChar123workspaceSlugChar125EventsDiffRoute
  '/_app/@{$workspaceSlug}/events/sandbox': typeof AppAtChar123workspaceSlugChar125EventsSandboxRoute
  '/_app/@{$workspaceSlug}/integrations/$integrationId': typeof AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute
  '/_app/@{$workspaceSlug}/plugins/$pluginId': typeof AppAtChar123workspaceSlugChar125PluginsPluginIdRoute
  '/_app/@{$workspaceSlug}/workflows/$workflowId': typeof AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute
  '/_app/@{$workspaceSlug}/workflows/new': typeof AppAtChar123workspaceSlugChar125WorkflowsNewRoute
  '/_app/@{$workspaceSlug}/~/settings': typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/_app/@{$workspaceSlug}/dlq/': typeof AppAtChar123workspaceSlugChar125DlqIndexRoute
  '/_app/@{$workspaceSlug}/events/': typeof AppAtChar123workspaceSlugChar125EventsIndexRoute
  '/_app/@{$workspaceSlug}/integrations/': typeof AppAtChar123workspaceSlugChar125IntegrationsIndexRoute
  '/_app/@{$workspaceSlug}/monitoring/': typeof AppAtChar123workspaceSlugChar125MonitoringIndexRoute
  '/_app/@{$workspaceSlug}/plugins/': typeof AppAtChar123workspaceSlugChar125PluginsIndexRoute
  '/_app/@{$workspaceSlug}/workflows/': typeof AppAtChar123workspaceSlugChar125WorkflowsIndexRoute
  '/_app/@{$workspaceSlug}/~/members/': typeof AppAtChar123workspaceSlugChar125Char126MembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/pricing'
    | '/api/_health'
    | '/oauth/callback'
    | '/oauth/error'
    | '/api/auth/$'
    | '/@{$workspaceSlug}/'
    | '/workspaces/'
    | '/@{$workspaceSlug}/events/$schemaName'
    | '/@{$workspaceSlug}/events/diff'
    | '/@{$workspaceSlug}/events/sandbox'
    | '/@{$workspaceSlug}/integrations/$integrationId'
    | '/@{$workspaceSlug}/plugins/$pluginId'
    | '/@{$workspaceSlug}/workflows/$workflowId'
    | '/@{$workspaceSlug}/workflows/new'
    | '/@{$workspaceSlug}/~/settings'
    | '/api/runs/$runId/stream'
    | '/@{$workspaceSlug}/dlq/'
    | '/@{$workspaceSlug}/events/'
    | '/@{$workspaceSlug}/integrations/'
    | '/@{$workspaceSlug}/monitoring/'
    | '/@{$workspaceSlug}/plugins/'
    | '/@{$workspaceSlug}/workflows/'
    | '/@{$workspaceSlug}/~/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/pricing'
    | '/api/_health'
    | '/oauth/callback'
    | '/oauth/error'
    | '/api/auth/$'
    | '/@{$workspaceSlug}'
    | '/workspaces'
    | '/@{$workspaceSlug}/events/$schemaName'
    | '/@{$workspaceSlug}/events/diff'
    | '/@{$workspaceSlug}/events/sandbox'
    | '/@{$workspaceSlug}/integrations/$integrationId'
    | '/@{$workspaceSlug}/plugins/$pluginId'
    | '/@{$workspaceSlug}/workflows/$workflowId'
    | '/@{$workspaceSlug}/workflows/new'
    | '/@{$workspaceSlug}/~/settings'
    | '/api/runs/$runId/stream'
    | '/@{$workspaceSlug}/dlq'
    | '/@{$workspaceSlug}/events'
    | '/@{$workspaceSlug}/integrations'
    | '/@{$workspaceSlug}/monitoring'
    | '/@{$workspaceSlug}/plugins'
    | '/@{$workspaceSlug}/workflows'
    | '/@{$workspaceSlug}/~/members'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/demo'
    | '/_public/pricing'
    | '/api/_health'
    | '/_public/'
    | '/_public/oauth/callback'
    | '/_public/oauth/error'
    | '/api/auth/$'
    | '/_app/@{$workspaceSlug}/'
    | '/_app/workspaces/'
    | '/_app/@{$workspaceSlug}/events/$schemaName'
    | '/_app/@{$workspaceSlug}/events/diff'
    | '/_app/@{$workspaceSlug}/events/sandbox'
    | '/_app/@{$workspaceSlug}/integrations/$integrationId'
    | '/_app/@{$workspaceSlug}/plugins/$pluginId'
    | '/_app/@{$workspaceSlug}/workflows/$workflowId'
    | '/_app/@{$workspaceSlug}/workflows/new'
    | '/_app/@{$workspaceSlug}/~/settings'
    | '/api/runs/$runId/stream'
    | '/_app/@{$workspaceSlug}/dlq/'
    | '/_app/@{$workspaceSlug}/events/'
    | '/_app/@{$workspaceSlug}/integrations/'
    | '/_app/@{$workspaceSlug}/monitoring/'
    | '/_app/@{$workspaceSlug}/plugins/'
    | '/_app/@{$workspaceSlug}/workflows/'
    | '/_app/@{$workspaceSlug}/~/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DemoRoute: typeof DemoRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRunsRunIdStreamRoute: typeof ApiRunsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/_health': {
      id: '/api/_health'
      path: '/api/_health'
      fullPath: '/api/_health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/': {
      id: '/_app/@{$workspaceSlug}/'
      path: '/@{$workspaceSlug}'
      fullPath: '/@{$workspaceSlug}/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125IndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/oauth/error': {
      id: '/_public/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof PublicOauthErrorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/oauth/callback': {
      id: '/_public/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof PublicOauthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/@{$workspaceSlug}/workflows/': {
      id: '/_app/@{$workspaceSlug}/workflows/'
      path: '/@{$workspaceSlug}/workflows'
      fullPath: '/@{$workspaceSlug}/workflows/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125WorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/plugins/': {
      id: '/_app/@{$workspaceSlug}/plugins/'
      path: '/@{$workspaceSlug}/plugins'
      fullPath: '/@{$workspaceSlug}/plugins/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125PluginsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/monitoring/': {
      id: '/_app/@{$workspaceSlug}/monitoring/'
      path: '/@{$workspaceSlug}/monitoring'
      fullPath: '/@{$workspaceSlug}/monitoring/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125MonitoringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/integrations/': {
      id: '/_app/@{$workspaceSlug}/integrations/'
      path: '/@{$workspaceSlug}/integrations'
      fullPath: '/@{$workspaceSlug}/integrations/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125IntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/events/': {
      id: '/_app/@{$workspaceSlug}/events/'
      path: '/@{$workspaceSlug}/events'
      fullPath: '/@{$workspaceSlug}/events/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125EventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/dlq/': {
      id: '/_app/@{$workspaceSlug}/dlq/'
      path: '/@{$workspaceSlug}/dlq'
      fullPath: '/@{$workspaceSlug}/dlq/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125DlqIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/runs/$runId/stream': {
      id: '/api/runs/$runId/stream'
      path: '/api/runs/$runId/stream'
      fullPath: '/api/runs/$runId/stream'
      preLoaderRoute: typeof ApiRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/@{$workspaceSlug}/~/settings': {
      id: '/_app/@{$workspaceSlug}/~/settings'
      path: '/@{$workspaceSlug}/~/settings'
      fullPath: '/@{$workspaceSlug}/~/settings'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125Char126SettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/workflows/new': {
      id: '/_app/@{$workspaceSlug}/workflows/new'
      path: '/@{$workspaceSlug}/workflows/new'
      fullPath: '/@{$workspaceSlug}/workflows/new'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125WorkflowsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/workflows/$workflowId': {
      id: '/_app/@{$workspaceSlug}/workflows/$workflowId'
      path: '/@{$workspaceSlug}/workflows/$workflowId'
      fullPath: '/@{$workspaceSlug}/workflows/$workflowId'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/plugins/$pluginId': {
      id: '/_app/@{$workspaceSlug}/plugins/$pluginId'
      path: '/@{$workspaceSlug}/plugins/$pluginId'
      fullPath: '/@{$workspaceSlug}/plugins/$pluginId'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125PluginsPluginIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/integrations/$integrationId': {
      id: '/_app/@{$workspaceSlug}/integrations/$integrationId'
      path: '/@{$workspaceSlug}/integrations/$integrationId'
      fullPath: '/@{$workspaceSlug}/integrations/$integrationId'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/events/sandbox': {
      id: '/_app/@{$workspaceSlug}/events/sandbox'
      path: '/@{$workspaceSlug}/events/sandbox'
      fullPath: '/@{$workspaceSlug}/events/sandbox'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125EventsSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/events/diff': {
      id: '/_app/@{$workspaceSlug}/events/diff'
      path: '/@{$workspaceSlug}/events/diff'
      fullPath: '/@{$workspaceSlug}/events/diff'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125EventsDiffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/events/$schemaName': {
      id: '/_app/@{$workspaceSlug}/events/$schemaName'
      path: '/@{$workspaceSlug}/events/$schemaName'
      fullPath: '/@{$workspaceSlug}/events/$schemaName'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125EventsSchemaNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/@{$workspaceSlug}/~/members/': {
      id: '/_app/@{$workspaceSlug}/~/members/'
      path: '/@{$workspaceSlug}/~/members'
      fullPath: '/@{$workspaceSlug}/~/members/'
      preLoaderRoute: typeof AppAtChar123workspaceSlugChar125Char126MembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAtChar123workspaceSlugChar125IndexRoute: typeof AppAtChar123workspaceSlugChar125IndexRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
  AppAtChar123workspaceSlugChar125EventsSchemaNameRoute: typeof AppAtChar123workspaceSlugChar125EventsSchemaNameRoute
  AppAtChar123workspaceSlugChar125EventsDiffRoute: typeof AppAtChar123workspaceSlugChar125EventsDiffRoute
  AppAtChar123workspaceSlugChar125EventsSandboxRoute: typeof AppAtChar123workspaceSlugChar125EventsSandboxRoute
  AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute: typeof AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute
  AppAtChar123workspaceSlugChar125PluginsPluginIdRoute: typeof AppAtChar123workspaceSlugChar125PluginsPluginIdRoute
  AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute: typeof AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute
  AppAtChar123workspaceSlugChar125WorkflowsNewRoute: typeof AppAtChar123workspaceSlugChar125WorkflowsNewRoute
  AppAtChar123workspaceSlugChar125Char126SettingsRoute: typeof AppAtChar123workspaceSlugChar125Char126SettingsRoute
  AppAtChar123workspaceSlugChar125DlqIndexRoute: typeof AppAtChar123workspaceSlugChar125DlqIndexRoute
  AppAtChar123workspaceSlugChar125EventsIndexRoute: typeof AppAtChar123workspaceSlugChar125EventsIndexRoute
  AppAtChar123workspaceSlugChar125IntegrationsIndexRoute: typeof AppAtChar123workspaceSlugChar125IntegrationsIndexRoute
  AppAtChar123workspaceSlugChar125MonitoringIndexRoute: typeof AppAtChar123workspaceSlugChar125MonitoringIndexRoute
  AppAtChar123workspaceSlugChar125PluginsIndexRoute: typeof AppAtChar123workspaceSlugChar125PluginsIndexRoute
  AppAtChar123workspaceSlugChar125WorkflowsIndexRoute: typeof AppAtChar123workspaceSlugChar125WorkflowsIndexRoute
  AppAtChar123workspaceSlugChar125Char126MembersIndexRoute: typeof AppAtChar123workspaceSlugChar125Char126MembersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtChar123workspaceSlugChar125IndexRoute:
    AppAtChar123workspaceSlugChar125IndexRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
  AppAtChar123workspaceSlugChar125EventsSchemaNameRoute:
    AppAtChar123workspaceSlugChar125EventsSchemaNameRoute,
  AppAtChar123workspaceSlugChar125EventsDiffRoute:
    AppAtChar123workspaceSlugChar125EventsDiffRoute,
  AppAtChar123workspaceSlugChar125EventsSandboxRoute:
    AppAtChar123workspaceSlugChar125EventsSandboxRoute,
  AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute:
    AppAtChar123workspaceSlugChar125IntegrationsIntegrationIdRoute,
  AppAtChar123workspaceSlugChar125PluginsPluginIdRoute:
    AppAtChar123workspaceSlugChar125PluginsPluginIdRoute,
  AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute:
    AppAtChar123workspaceSlugChar125WorkflowsWorkflowIdRoute,
  AppAtChar123workspaceSlugChar125WorkflowsNewRoute:
    AppAtChar123workspaceSlugChar125WorkflowsNewRoute,
  AppAtChar123workspaceSlugChar125Char126SettingsRoute:
    AppAtChar123workspaceSlugChar125Char126SettingsRoute,
  AppAtChar123workspaceSlugChar125DlqIndexRoute:
    AppAtChar123workspaceSlugChar125DlqIndexRoute,
  AppAtChar123workspaceSlugChar125EventsIndexRoute:
    AppAtChar123workspaceSlugChar125EventsIndexRoute,
  AppAtChar123workspaceSlugChar125IntegrationsIndexRoute:
    AppAtChar123workspaceSlugChar125IntegrationsIndexRoute,
  AppAtChar123workspaceSlugChar125MonitoringIndexRoute:
    AppAtChar123workspaceSlugChar125MonitoringIndexRoute,
  AppAtChar123workspaceSlugChar125PluginsIndexRoute:
    AppAtChar123workspaceSlugChar125PluginsIndexRoute,
  AppAtChar123workspaceSlugChar125WorkflowsIndexRoute:
    AppAtChar123workspaceSlugChar125WorkflowsIndexRoute,
  AppAtChar123workspaceSlugChar125Char126MembersIndexRoute:
    AppAtChar123workspaceSlugChar125Char126MembersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicOauthCallbackRoute: typeof PublicOauthCallbackRoute
  PublicOauthErrorRoute: typeof PublicOauthErrorRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOauthCallbackRoute: PublicOauthCallbackRoute,
  PublicOauthErrorRoute: PublicOauthErrorRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DemoRoute: DemoRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRunsRunIdStreamRoute: ApiRunsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
