/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiExecuteWorkflowRouteImport } from './routes/api/execute-workflow'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as AuthWorkspacesIndexRouteImport } from './routes/_auth/workspaces/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicOauthErrorRouteImport } from './routes/_public/oauth/error'
import { Route as PublicOauthCallbackRouteImport } from './routes/_public/oauth/callback'
import { Route as AuthWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/index'
import { Route as ApiRunsRunIdStreamRouteImport } from './routes/api/runs/$runId/stream'
import { Route as AuthWorkspacesWorkspaceSlugSettingsRouteImport } from './routes/_auth/workspaces/$workspaceSlug/settings'
import { Route as AuthWorkspacesWorkspaceSlugWorkflowsIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/workflows/index'
import { Route as AuthWorkspacesWorkspaceSlugPluginsIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/plugins/index'
import { Route as AuthWorkspacesWorkspaceSlugIntegrationsIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/integrations/index'
import { Route as AuthWorkspacesWorkspaceSlugEventsIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/events/index'
import { Route as AuthWorkspacesWorkspaceSlugDlqIndexRouteImport } from './routes/_auth/workspaces/$workspaceSlug/dlq/index'
import { Route as AuthWorkspacesWorkspaceSlugWorkflowsNewRouteImport } from './routes/_auth/workspaces/$workspaceSlug/workflows/new'
import { Route as AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRouteImport } from './routes/_auth/workspaces/$workspaceSlug/workflows/$workflowId'
import { Route as AuthWorkspacesWorkspaceSlugPluginsPluginIdRouteImport } from './routes/_auth/workspaces/$workspaceSlug/plugins/$pluginId'
import { Route as AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRouteImport } from './routes/_auth/workspaces/$workspaceSlug/integrations/$integrationId'
import { Route as AuthWorkspacesWorkspaceSlugEventsSandboxRouteImport } from './routes/_auth/workspaces/$workspaceSlug/events/sandbox'
import { Route as AuthWorkspacesWorkspaceSlugEventsDiffRouteImport } from './routes/_auth/workspaces/$workspaceSlug/events/diff'
import { Route as AuthWorkspacesWorkspaceSlugEventsSchemaNameRouteImport } from './routes/_auth/workspaces/$workspaceSlug/events/$schemaName'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiExecuteWorkflowRoute = ApiExecuteWorkflowRouteImport.update({
  id: '/api/execute-workflow',
  path: '/api/execute-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const AuthWorkspacesIndexRoute = AuthWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOauthErrorRoute = PublicOauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOauthCallbackRoute = PublicOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const AuthWorkspacesWorkspaceSlugIndexRoute =
  AuthWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/',
    path: '/workspaces/$workspaceSlug/',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiRunsRunIdStreamRoute = ApiRunsRunIdStreamRouteImport.update({
  id: '/api/runs/$runId/stream',
  path: '/api/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspacesWorkspaceSlugSettingsRoute =
  AuthWorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/workspaces/$workspaceSlug/settings',
    path: '/workspaces/$workspaceSlug/settings',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute =
  AuthWorkspacesWorkspaceSlugWorkflowsIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/workflows/',
    path: '/workspaces/$workspaceSlug/workflows/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugPluginsIndexRoute =
  AuthWorkspacesWorkspaceSlugPluginsIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/plugins/',
    path: '/workspaces/$workspaceSlug/plugins/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute =
  AuthWorkspacesWorkspaceSlugIntegrationsIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/integrations/',
    path: '/workspaces/$workspaceSlug/integrations/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugEventsIndexRoute =
  AuthWorkspacesWorkspaceSlugEventsIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/events/',
    path: '/workspaces/$workspaceSlug/events/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugDlqIndexRoute =
  AuthWorkspacesWorkspaceSlugDlqIndexRouteImport.update({
    id: '/workspaces/$workspaceSlug/dlq/',
    path: '/workspaces/$workspaceSlug/dlq/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugWorkflowsNewRoute =
  AuthWorkspacesWorkspaceSlugWorkflowsNewRouteImport.update({
    id: '/workspaces/$workspaceSlug/workflows/new',
    path: '/workspaces/$workspaceSlug/workflows/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute =
  AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRouteImport.update({
    id: '/workspaces/$workspaceSlug/workflows/$workflowId',
    path: '/workspaces/$workspaceSlug/workflows/$workflowId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute =
  AuthWorkspacesWorkspaceSlugPluginsPluginIdRouteImport.update({
    id: '/workspaces/$workspaceSlug/plugins/$pluginId',
    path: '/workspaces/$workspaceSlug/plugins/$pluginId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute =
  AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRouteImport.update({
    id: '/workspaces/$workspaceSlug/integrations/$integrationId',
    path: '/workspaces/$workspaceSlug/integrations/$integrationId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugEventsSandboxRoute =
  AuthWorkspacesWorkspaceSlugEventsSandboxRouteImport.update({
    id: '/workspaces/$workspaceSlug/events/sandbox',
    path: '/workspaces/$workspaceSlug/events/sandbox',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugEventsDiffRoute =
  AuthWorkspacesWorkspaceSlugEventsDiffRouteImport.update({
    id: '/workspaces/$workspaceSlug/events/diff',
    path: '/workspaces/$workspaceSlug/events/diff',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute =
  AuthWorkspacesWorkspaceSlugEventsSchemaNameRouteImport.update({
    id: '/workspaces/$workspaceSlug/events/$schemaName',
    path: '/workspaces/$workspaceSlug/events/$schemaName',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/pricing': typeof PublicPricingRoute
  '/api/execute-workflow': typeof ApiExecuteWorkflowRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/': typeof AuthWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/workspaces/$workspaceSlug/': typeof AuthWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/events/$schemaName': typeof AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute
  '/workspaces/$workspaceSlug/events/diff': typeof AuthWorkspacesWorkspaceSlugEventsDiffRoute
  '/workspaces/$workspaceSlug/events/sandbox': typeof AuthWorkspacesWorkspaceSlugEventsSandboxRoute
  '/workspaces/$workspaceSlug/integrations/$integrationId': typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  '/workspaces/$workspaceSlug/plugins/$pluginId': typeof AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute
  '/workspaces/$workspaceSlug/workflows/$workflowId': typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  '/workspaces/$workspaceSlug/workflows/new': typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  '/workspaces/$workspaceSlug/dlq/': typeof AuthWorkspacesWorkspaceSlugDlqIndexRoute
  '/workspaces/$workspaceSlug/events/': typeof AuthWorkspacesWorkspaceSlugEventsIndexRoute
  '/workspaces/$workspaceSlug/integrations/': typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  '/workspaces/$workspaceSlug/plugins/': typeof AuthWorkspacesWorkspaceSlugPluginsIndexRoute
  '/workspaces/$workspaceSlug/workflows/': typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/pricing': typeof PublicPricingRoute
  '/api/execute-workflow': typeof ApiExecuteWorkflowRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/workspaces/$workspaceSlug': typeof AuthWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/events/$schemaName': typeof AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute
  '/workspaces/$workspaceSlug/events/diff': typeof AuthWorkspacesWorkspaceSlugEventsDiffRoute
  '/workspaces/$workspaceSlug/events/sandbox': typeof AuthWorkspacesWorkspaceSlugEventsSandboxRoute
  '/workspaces/$workspaceSlug/integrations/$integrationId': typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  '/workspaces/$workspaceSlug/plugins/$pluginId': typeof AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute
  '/workspaces/$workspaceSlug/workflows/$workflowId': typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  '/workspaces/$workspaceSlug/workflows/new': typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  '/workspaces/$workspaceSlug/dlq': typeof AuthWorkspacesWorkspaceSlugDlqIndexRoute
  '/workspaces/$workspaceSlug/events': typeof AuthWorkspacesWorkspaceSlugEventsIndexRoute
  '/workspaces/$workspaceSlug/integrations': typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  '/workspaces/$workspaceSlug/plugins': typeof AuthWorkspacesWorkspaceSlugPluginsIndexRoute
  '/workspaces/$workspaceSlug/workflows': typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/pricing': typeof PublicPricingRoute
  '/api/execute-workflow': typeof ApiExecuteWorkflowRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/oauth/callback': typeof PublicOauthCallbackRoute
  '/_public/oauth/error': typeof PublicOauthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/workspaces/': typeof AuthWorkspacesIndexRoute
  '/_auth/workspaces/$workspaceSlug/settings': typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
  '/_auth/workspaces/$workspaceSlug/': typeof AuthWorkspacesWorkspaceSlugIndexRoute
  '/_auth/workspaces/$workspaceSlug/events/$schemaName': typeof AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute
  '/_auth/workspaces/$workspaceSlug/events/diff': typeof AuthWorkspacesWorkspaceSlugEventsDiffRoute
  '/_auth/workspaces/$workspaceSlug/events/sandbox': typeof AuthWorkspacesWorkspaceSlugEventsSandboxRoute
  '/_auth/workspaces/$workspaceSlug/integrations/$integrationId': typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  '/_auth/workspaces/$workspaceSlug/plugins/$pluginId': typeof AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute
  '/_auth/workspaces/$workspaceSlug/workflows/$workflowId': typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  '/_auth/workspaces/$workspaceSlug/workflows/new': typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  '/_auth/workspaces/$workspaceSlug/dlq/': typeof AuthWorkspacesWorkspaceSlugDlqIndexRoute
  '/_auth/workspaces/$workspaceSlug/events/': typeof AuthWorkspacesWorkspaceSlugEventsIndexRoute
  '/_auth/workspaces/$workspaceSlug/integrations/': typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  '/_auth/workspaces/$workspaceSlug/plugins/': typeof AuthWorkspacesWorkspaceSlugPluginsIndexRoute
  '/_auth/workspaces/$workspaceSlug/workflows/': typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/api/execute-workflow'
    | '/oauth/callback'
    | '/oauth/error'
    | '/api/auth/$'
    | '/workspaces/'
    | '/workspaces/$workspaceSlug/settings'
    | '/api/runs/$runId/stream'
    | '/workspaces/$workspaceSlug/'
    | '/workspaces/$workspaceSlug/events/$schemaName'
    | '/workspaces/$workspaceSlug/events/diff'
    | '/workspaces/$workspaceSlug/events/sandbox'
    | '/workspaces/$workspaceSlug/integrations/$integrationId'
    | '/workspaces/$workspaceSlug/plugins/$pluginId'
    | '/workspaces/$workspaceSlug/workflows/$workflowId'
    | '/workspaces/$workspaceSlug/workflows/new'
    | '/workspaces/$workspaceSlug/dlq/'
    | '/workspaces/$workspaceSlug/events/'
    | '/workspaces/$workspaceSlug/integrations/'
    | '/workspaces/$workspaceSlug/plugins/'
    | '/workspaces/$workspaceSlug/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/api/execute-workflow'
    | '/oauth/callback'
    | '/oauth/error'
    | '/api/auth/$'
    | '/workspaces'
    | '/workspaces/$workspaceSlug/settings'
    | '/api/runs/$runId/stream'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/$workspaceSlug/events/$schemaName'
    | '/workspaces/$workspaceSlug/events/diff'
    | '/workspaces/$workspaceSlug/events/sandbox'
    | '/workspaces/$workspaceSlug/integrations/$integrationId'
    | '/workspaces/$workspaceSlug/plugins/$pluginId'
    | '/workspaces/$workspaceSlug/workflows/$workflowId'
    | '/workspaces/$workspaceSlug/workflows/new'
    | '/workspaces/$workspaceSlug/dlq'
    | '/workspaces/$workspaceSlug/events'
    | '/workspaces/$workspaceSlug/integrations'
    | '/workspaces/$workspaceSlug/plugins'
    | '/workspaces/$workspaceSlug/workflows'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_public/pricing'
    | '/api/execute-workflow'
    | '/_public/'
    | '/_public/oauth/callback'
    | '/_public/oauth/error'
    | '/api/auth/$'
    | '/_auth/workspaces/'
    | '/_auth/workspaces/$workspaceSlug/settings'
    | '/api/runs/$runId/stream'
    | '/_auth/workspaces/$workspaceSlug/'
    | '/_auth/workspaces/$workspaceSlug/events/$schemaName'
    | '/_auth/workspaces/$workspaceSlug/events/diff'
    | '/_auth/workspaces/$workspaceSlug/events/sandbox'
    | '/_auth/workspaces/$workspaceSlug/integrations/$integrationId'
    | '/_auth/workspaces/$workspaceSlug/plugins/$pluginId'
    | '/_auth/workspaces/$workspaceSlug/workflows/$workflowId'
    | '/_auth/workspaces/$workspaceSlug/workflows/new'
    | '/_auth/workspaces/$workspaceSlug/dlq/'
    | '/_auth/workspaces/$workspaceSlug/events/'
    | '/_auth/workspaces/$workspaceSlug/integrations/'
    | '/_auth/workspaces/$workspaceSlug/plugins/'
    | '/_auth/workspaces/$workspaceSlug/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiExecuteWorkflowRoute: typeof ApiExecuteWorkflowRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRunsRunIdStreamRoute: typeof ApiRunsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/execute-workflow': {
      id: '/api/execute-workflow'
      path: '/api/execute-workflow'
      fullPath: '/api/execute-workflow'
      preLoaderRoute: typeof ApiExecuteWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/workspaces/': {
      id: '/_auth/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthWorkspacesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/oauth/error': {
      id: '/_public/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof PublicOauthErrorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/oauth/callback': {
      id: '/_public/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof PublicOauthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/workspaces/$workspaceSlug/': {
      id: '/_auth/workspaces/$workspaceSlug/'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/runs/$runId/stream': {
      id: '/api/runs/$runId/stream'
      path: '/api/runs/$runId/stream'
      fullPath: '/api/runs/$runId/stream'
      preLoaderRoute: typeof ApiRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/workspaces/$workspaceSlug/settings': {
      id: '/_auth/workspaces/$workspaceSlug/settings'
      path: '/workspaces/$workspaceSlug/settings'
      fullPath: '/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/workflows/': {
      id: '/_auth/workspaces/$workspaceSlug/workflows/'
      path: '/workspaces/$workspaceSlug/workflows'
      fullPath: '/workspaces/$workspaceSlug/workflows/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/plugins/': {
      id: '/_auth/workspaces/$workspaceSlug/plugins/'
      path: '/workspaces/$workspaceSlug/plugins'
      fullPath: '/workspaces/$workspaceSlug/plugins/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugPluginsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/integrations/': {
      id: '/_auth/workspaces/$workspaceSlug/integrations/'
      path: '/workspaces/$workspaceSlug/integrations'
      fullPath: '/workspaces/$workspaceSlug/integrations/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/events/': {
      id: '/_auth/workspaces/$workspaceSlug/events/'
      path: '/workspaces/$workspaceSlug/events'
      fullPath: '/workspaces/$workspaceSlug/events/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugEventsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/dlq/': {
      id: '/_auth/workspaces/$workspaceSlug/dlq/'
      path: '/workspaces/$workspaceSlug/dlq'
      fullPath: '/workspaces/$workspaceSlug/dlq/'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugDlqIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/workflows/new': {
      id: '/_auth/workspaces/$workspaceSlug/workflows/new'
      path: '/workspaces/$workspaceSlug/workflows/new'
      fullPath: '/workspaces/$workspaceSlug/workflows/new'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/workflows/$workflowId': {
      id: '/_auth/workspaces/$workspaceSlug/workflows/$workflowId'
      path: '/workspaces/$workspaceSlug/workflows/$workflowId'
      fullPath: '/workspaces/$workspaceSlug/workflows/$workflowId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/plugins/$pluginId': {
      id: '/_auth/workspaces/$workspaceSlug/plugins/$pluginId'
      path: '/workspaces/$workspaceSlug/plugins/$pluginId'
      fullPath: '/workspaces/$workspaceSlug/plugins/$pluginId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugPluginsPluginIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/integrations/$integrationId': {
      id: '/_auth/workspaces/$workspaceSlug/integrations/$integrationId'
      path: '/workspaces/$workspaceSlug/integrations/$integrationId'
      fullPath: '/workspaces/$workspaceSlug/integrations/$integrationId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/events/sandbox': {
      id: '/_auth/workspaces/$workspaceSlug/events/sandbox'
      path: '/workspaces/$workspaceSlug/events/sandbox'
      fullPath: '/workspaces/$workspaceSlug/events/sandbox'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugEventsSandboxRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/events/diff': {
      id: '/_auth/workspaces/$workspaceSlug/events/diff'
      path: '/workspaces/$workspaceSlug/events/diff'
      fullPath: '/workspaces/$workspaceSlug/events/diff'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugEventsDiffRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceSlug/events/$schemaName': {
      id: '/_auth/workspaces/$workspaceSlug/events/$schemaName'
      path: '/workspaces/$workspaceSlug/events/$schemaName'
      fullPath: '/workspaces/$workspaceSlug/events/$schemaName'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceSlugEventsSchemaNameRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthWorkspacesIndexRoute: typeof AuthWorkspacesIndexRoute
  AuthWorkspacesWorkspaceSlugSettingsRoute: typeof AuthWorkspacesWorkspaceSlugSettingsRoute
  AuthWorkspacesWorkspaceSlugIndexRoute: typeof AuthWorkspacesWorkspaceSlugIndexRoute
  AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute: typeof AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute
  AuthWorkspacesWorkspaceSlugEventsDiffRoute: typeof AuthWorkspacesWorkspaceSlugEventsDiffRoute
  AuthWorkspacesWorkspaceSlugEventsSandboxRoute: typeof AuthWorkspacesWorkspaceSlugEventsSandboxRoute
  AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute
  AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute: typeof AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute
  AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute
  AuthWorkspacesWorkspaceSlugWorkflowsNewRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsNewRoute
  AuthWorkspacesWorkspaceSlugDlqIndexRoute: typeof AuthWorkspacesWorkspaceSlugDlqIndexRoute
  AuthWorkspacesWorkspaceSlugEventsIndexRoute: typeof AuthWorkspacesWorkspaceSlugEventsIndexRoute
  AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute: typeof AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute
  AuthWorkspacesWorkspaceSlugPluginsIndexRoute: typeof AuthWorkspacesWorkspaceSlugPluginsIndexRoute
  AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute: typeof AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWorkspacesIndexRoute: AuthWorkspacesIndexRoute,
  AuthWorkspacesWorkspaceSlugSettingsRoute:
    AuthWorkspacesWorkspaceSlugSettingsRoute,
  AuthWorkspacesWorkspaceSlugIndexRoute: AuthWorkspacesWorkspaceSlugIndexRoute,
  AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute:
    AuthWorkspacesWorkspaceSlugEventsSchemaNameRoute,
  AuthWorkspacesWorkspaceSlugEventsDiffRoute:
    AuthWorkspacesWorkspaceSlugEventsDiffRoute,
  AuthWorkspacesWorkspaceSlugEventsSandboxRoute:
    AuthWorkspacesWorkspaceSlugEventsSandboxRoute,
  AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute:
    AuthWorkspacesWorkspaceSlugIntegrationsIntegrationIdRoute,
  AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute:
    AuthWorkspacesWorkspaceSlugPluginsPluginIdRoute,
  AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute:
    AuthWorkspacesWorkspaceSlugWorkflowsWorkflowIdRoute,
  AuthWorkspacesWorkspaceSlugWorkflowsNewRoute:
    AuthWorkspacesWorkspaceSlugWorkflowsNewRoute,
  AuthWorkspacesWorkspaceSlugDlqIndexRoute:
    AuthWorkspacesWorkspaceSlugDlqIndexRoute,
  AuthWorkspacesWorkspaceSlugEventsIndexRoute:
    AuthWorkspacesWorkspaceSlugEventsIndexRoute,
  AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute:
    AuthWorkspacesWorkspaceSlugIntegrationsIndexRoute,
  AuthWorkspacesWorkspaceSlugPluginsIndexRoute:
    AuthWorkspacesWorkspaceSlugPluginsIndexRoute,
  AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute:
    AuthWorkspacesWorkspaceSlugWorkflowsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicOauthCallbackRoute: typeof PublicOauthCallbackRoute
  PublicOauthErrorRoute: typeof PublicOauthErrorRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOauthCallbackRoute: PublicOauthCallbackRoute,
  PublicOauthErrorRoute: PublicOauthErrorRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiExecuteWorkflowRoute: ApiExecuteWorkflowRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRunsRunIdStreamRoute: ApiRunsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
